kind: pipeline
name: default

steps:
  - name: testing
    image: cypress/browsers:chrome69
    environment:
      CYPRESS_baseUrl: http://jsonplaceholder.typicode.com
    commands:
      - $(npm bin)/cypress install
      - $(npm bin)/cypress run --browser chrome
  when:
   branch:
    - master
  event:
   - push
   - pull-request